### ISSUE TITLE
Commands not found with usage 

### ISSUE THREAD

**Issue by prateekmanocha** [andiwand/ptbridge#6]
usage: <ptbridge>  [<interface> <pt_ip>:<pt_port> <password>]

default: eth0 192.168.15.101:38000 cisco
root@prateek-desktop:~/ptbridge-master# eth0 192.168.15.192:38000 cisco
eth0: command not found

Please explain how to call and also is there anz need to call the ptbridge.jar using java -jar command ?

**Comment by andiwand** [comment]
like shown in the readme:

./ptbridge <interface> <pt_ip>:<pt_port> <password>
